image: openjdk:17

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir -p build/classes
    - bash -c 'shopt -s globstar; javac -d build/classes **/*.java'
  artifacts:
    paths:
      - build/classes
    expire_in: 1h

test:
  stage: test
  script:
    - wget -q https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar
    - java -jar junit-platform-console-standalone-1.9.2.jar \
      --class-path build/classes \
      --scan-class-path \
      --reports-dir junit-reports
  artifacts:
    when: always
    reports:
      junit: junit-reports/*.xml
